function namesObjArr() {
  let characters = [
    {
      short: 'eichi',
      id: {sort: 1, asset: 22},
      unit: 'fine',
      type: 'idol',
      jp: {regular: '天祥院 英智', alt: ''},
      rom: {regular: 'Tenshouin Eichi', alt: ''},
      cn: {regular: '天祥院 英智', alt: ''},
      kr: {regular: '텐쇼인 에이치', alt: ''},
      tw: {regular: '天祥院 英智', alt: ''},
      en: {regular: 'Eichi Tenshouin', alt: ''},
    },
    {
      short: 'wataru',
      id: {sort: 2, asset: 27},
      unit: 'fine',
      type: 'idol',
      jp: {regular: '日々樹 渉', alt: ''},
      rom: {regular: 'Hibiki Wataru', alt: ''},
      cn: {regular: '日日树 涉', alt: ''},
      kr: {regular: '히비키 와타루', alt: ''},
      tw: {regular: '日日樹 涉', alt: ''},
      en: {regular: 'Wataru Hibiki', alt: ''},
    },
    {
      short: 'tori',
      id: {sort: 3, asset: 6},
      unit: 'fine',
      type: 'idol',
      jp: {regular: '姫宮 桃李', alt: ''},
      rom: {regular: 'Himemiya Tori', alt: ''},
      cn: {regular: '姬宫 桃李', alt: ''},
      kr: {regular: '히메미야 토리', alt: ''},
      tw: {regular: '姬宫 桃李', alt: ''},
      en: {regular: 'Tori Himemiya', alt: ''},
    },
    {
      short: 'yuzuru',
      id: {sort: 4, asset: 19},
      unit: 'fine',
      type: 'idol',
      jp: {regular: '伏見 弓弦', alt: ''},
      rom: {regular: 'Fushimi Yuzuru', alt: ''},
      cn: {regular: '伏见 弓弦', alt: ''},
      kr: {regular: '후시미 유즈루', alt: ''},
      tw: {regular: '伏見 弓弦', alt: ''},
      en: {regular: 'Yuzuru Fushimi', alt: ''},
    },
    {
      short: 'hokuto',
      id: {sort: 11, asset: 12},
      unit: 'Trickstar',
      type: 'idol',
      jp: {regular: '氷鷹 北斗', alt: ''},
      rom: {regular: 'Hidaka Hokuto', alt: ''},
      cn: {regular: '冰鹰 北斗', alt: ''},
      kr: {regular: '히다카 호쿠토', alt: ''},
      tw: {regular: '冰鷹 北斗', alt: ''},
      en: {regular: 'Hokuto Hidaka', alt: ''},
    },
    {
      short: 'subaru',
      id: {sort: 12, asset: 11},
      unit: 'Trickstar',
      type: 'idol',
      jp: {regular: '明星 スバル', alt: ''},
      rom: {regular: 'Akehoshi Subaru', alt: ''},
      cn: {regular: '明星 昴流', alt: ''},
      kr: {regular: '아케호시 스바루', alt: ''},
      tw: {regular: '明星 昴流', alt: ''},
      en: {regular: 'Subaru Akehoshi', alt: ''},
    },
    {
      short: 'makoto',
      id: {sort: 13, asset: 13},
      unit: 'Trickstar',
      type: 'idol',
      jp: {regular: '遊木 真', alt: ''},
      rom: {regular: 'Yuuki Makoto', alt: ''},
      cn: {regular: '游木 真', alt: ''},
      kr: {regular: '유우키 마코토', alt: ''},
      tw: {regular: '遊木 真', alt: ''},
      en: {regular: 'Makoto Yuuki', alt: ''},
    },
    {
      short: 'mao',
      id: {sort: 14, asset: 18},
      unit: 'Trickstar',
      type: 'idol',
      jp: {regular: '衣更 真緒', alt: ''},
      rom: {regular: 'Isara Mao', alt: ''},
      cn: {regular: '衣更 真绪', alt: ''},
      kr: {regular: '이사라 마오', alt: ''},
      tw: {regular: '衣更 真緒', alt: ''},
      en: {regular: 'Mao Isara', alt: ''},
    },
    {
      short: 'tetora',
      id: {sort: 21, asset: 1},
      unit: 'RYUSEITAI',
      type: 'idol',
      jp: {regular: '南雲 鉄虎', alt: ''},
      rom: {regular: 'Nagumo Tetora', alt: ''},
      cn: {regular: '南云 铁虎', alt: ''},
      kr: {regular: '나구모 테토라', alt: ''},
      tw: {regular: '南雲 鐵虎', alt: ''},
      en: {regular: 'Tetora Nagumo', alt: ''},
    },
    {
      short: 'midori',
      id: {sort: 22, asset: 5},
      unit: 'RYUSEITAI',
      type: 'idol',
      jp: {regular: '高峯 翠', alt: ''},
      rom: {regular: 'Takamine Midori', alt: ''},
      cn: {regular: '高峯 翠', alt: ''},
      kr: {regular: '타카미네 미도리', alt: ''},
      tw: {regular: '高峯 翠', alt: ''},
      en: {regular: 'Midori Takamine', alt: ''},
    },
    {
      short: 'shinobu',
      id: {sort: 23, asset: 7},
      unit: 'RYUSEITAI',
      type: 'idol',
      jp: {regular: '仙石 忍', alt: ''},
      rom: {regular: 'Sengoku Shinobu', alt: ''},
      cn: {regular: '仙石 忍', alt: ''},
      kr: {regular: '센고쿠 시노부', alt: ''},
      tw: {regular: '仙石 忍', alt: ''},
      en: {regular: 'Shinobu Sengoku', alt: ''},
    },
    {
      short: 'chiaki',
      id: {sort: 24, asset: 25},
      unit: 'RYUSEITAI',
      type: 'idol',
      jp: {regular: '守沢 千秋', alt: ''},
      rom: {regular: 'Morisawa Chiaki', alt: ''},
      cn: {regular: '守泽 千秋', alt: ''},
      kr: {regular: '모리사와 치아키', alt: ''},
      tw: {regular: '守澤 千秋', alt: ''},
      en: {regular: 'Chiaki Morisawa', alt: ''},
    },
    {
      short: 'kanata',
      id: {sort: 25, asset: 28},
      unit: 'RYUSEITAI',
      type: 'idol',
      jp: {regular: '深海 奏汰', alt: ''},
      rom: {regular: 'Shinkai Kanata', alt: ''},
      cn: {regular: '深海 奏汰', alt: ''},
      kr: {regular: '신카이 카나타', alt: ''},
      tw: {regular: '深海 奏汰', alt: ''},
      en: {regular: 'Kanata Shinkai', alt: ''},
    },
    {
      short: 'hiiro',
      id: {sort: 31, asset: 67},
      unit: 'ALKALOID',
      type: 'idol',
      jp: {regular: '天城 一彩', alt: ''},
      rom: {regular: 'Amagi Hiiro', alt: ''},
      cn: {regular: '天城 一彩', alt: ''},
      kr: {regular: '아마기 히이로', alt: ''},
      tw: {regular: '天城 一彩', alt: ''},
      en: {regular: 'Hiiro Amagi', alt: ''},
    },
    {
      short: 'aira',
      id: {sort: 32, asset: 68},
      unit: 'ALKALOID',
      type: 'idol',
      jp: {regular: '白鳥 藍良', alt: ''},
      rom: {regular: 'Shiratori Aira', alt: ''},
      cn: {regular: '白鸟 蓝良', alt: ''},
      kr: {regular: '시라토리 아이라', alt: ''},
      tw: {regular: '白鳥 藍良', alt: ''},
      en: {regular: 'Aira Shiratori', alt: ''},
    },
    {
      short: 'mayoi',
      id: {sort: 33, asset: 69},
      unit: 'ALKALOID',
      type: 'idol',
      jp: {regular: '礼瀬 マヨイ', alt: ''},
      rom: {regular: 'Ayase Mayoi', alt: ''},
      cn: {regular: '礼濑 真宵', alt: ''},
      kr: {regular: '아야세 마요이', alt: ''},
      tw: {regular: '禮瀨 真宵', alt: ''},
      en: {regular: 'Mayoi Ayase', alt: ''},
    },
    {
      short: 'tatsumi',
      id: {sort: 34, asset: 70},
      unit: 'ALKALOID',
      type: 'idol',
      jp: {regular: '風早 巽', alt: ''},
      rom: {regular: 'Kazehaya Tatsumi', alt: ''},
      cn: {regular: '风早 巽', alt: ''},
      kr: {regular: '카제하야 타츠미', alt: ''},
      tw: {regular: '風早 巽', alt: ''},
      en: {regular: 'Tatsumi Kazehaya', alt: ''},
    },
    {
      short: 'nagisa',
      id: {sort: 41, asset: 50},
      unit: 'Eden',
      type: 'idol',
      jp: {regular: '乱 凪砂', alt: ''},
      rom: {regular: 'Ran Nagisa', alt: ''},
      cn: {regular: '乱 凪砂', alt: ''},
      kr: {regular: '란 나기사', alt: ''},
      tw: {regular: '亂 凪砂', alt: ''},
      en: {regular: 'Nagisa Ran', alt: ''},
    },
    {
      short: 'hiyori',
      id: {sort: 42, asset: 41},
      unit: 'Eden',
      type: 'idol',
      jp: {regular: '巴 日和', alt: ''},
      rom: {regular: 'Tomoe Hiyori', alt: ''},
      cn: {regular: '巴 日和', alt: ''},
      kr: {regular: '토모에 히요리', alt: ''},
      tw: {regular: '巴 日和', alt: ''},
      en: {regular: 'Hiyori Tomoe', alt: ''},
    },
    {
      short: 'ibara',
      id: {sort: 43, asset: 51},
      unit: 'Eden',
      type: 'idol',
      jp: {regular: '七種 茨', alt: ''},
      rom: {regular: 'Saegusa Ibara', alt: ''},
      cn: {regular: '七种 茨', alt: ''},
      kr: {regular: '사에구사 이바라', alt: ''},
      tw: {regular: '七種 茨', alt: ''},
      en: {regular: 'Ibara Saegusa', alt: ''},
    },
    {
      short: 'jun',
      id: {sort: 44, asset: 42},
      unit: 'Eden',
      type: 'idol',
      jp: {regular: '漣 ジュン', alt: ''},
      rom: {regular: 'Sazanami Jun', alt: ''},
      cn: {regular: '涟 纯', alt: ''},
      kr: {regular: '사자나미 쥰', alt: ''},
      tw: {regular: '漣 純', alt: ''},
      en: {regular: 'Jun Sazanami', alt: ''},
    },
    {
      short: 'shu',
      id: {sort: 51, asset: 35},
      unit: 'Valkyrie',
      type: 'idol',
      jp: {regular: '斎宮 宗', alt: ''},
      rom: {regular: 'Itsuki Shu', alt: ''},
      cn: {regular: '斋宫 宗', alt: ''},
      kr: {regular: '이츠키 슈', alt: ''},
      tw: {regular: '齋宮 宗', alt: ''},
      en: {regular: 'Shu Itsuki', alt: ''},
    },
    {
      short: 'mika',
      id: {sort: 52, asset: 34},
      unit: 'Valkyrie',
      type: 'idol',
      jp: {regular: '影片 みか', alt: ''},
      rom: {regular: 'Kagehira Mika', alt: ''},
      cn: {regular: '影片 美伽', alt: ''},
      kr: {regular: '카게히라 미카', alt: ''},
      tw: {regular: '影片 美咖', alt: ''},
      en: {regular: 'Mika Kagehira', alt: ''},
    },
    {
      short: 'hinata',
      id: {sort: 61, asset: 4},
      unit: '2wink',
      type: 'idol',
      jp: {regular: '葵 ひなた', alt: ''},
      rom: {regular: 'Aoi Hinata', alt: ''},
      cn: {regular: '葵 日向', alt: ''},
      kr: {regular: '아오이 히나타', alt: ''},
      tw: {regular: '葵 日向', alt: ''},
      en: {regular: 'Hinata Aoi', alt: ''},
    },
    {
      short: 'yuuta',
      id: {sort: 62, asset: 8},
      unit: '2wink',
      type: 'idol',
      jp: {regular: '葵 ゆうた', alt: ''},
      rom: {regular: 'Aoi Yuuta', alt: ''},
      cn: {regular: '葵 裕太', alt: ''},
      kr: {regular: '아오이 유우타', alt: ''},
      tw: {regular: '葵 裕太', alt: ''},
      en: {regular: 'Yuta Aoi', alt: ''},
    },
    {
      short: 'rinne',
      id: {sort: 71, asset: 71},
      unit: 'Crazy:B',
      type: 'idol',
      jp: {regular: '天城 燐音', alt: ''},
      rom: {regular: 'Amagi Rinne', alt: ''},
      cn: {regular: '天城 燐音', alt: ''},
      kr: {regular: '아마기 린네', alt: ''},
      tw: {regular: '天城 燐音', alt: ''},
      en: {regular: 'Rinne Amagi', alt: ''},
    },
    {
      short: 'himeru',
      id: {sort: 72, asset: 72},
      unit: 'Crazy:B',
      type: 'idol',
      jp: {regular: 'HiMERU', alt: ''},
      rom: {regular: 'HiMERU', alt: ''},
      cn: {regular: 'HiMERU', alt: ''},
      kr: {regular: 'HiMERU', alt: ''},
      tw: {regular: 'HiMERU', alt: ''},
      en: {regular: 'HiMERU', alt: ''},
    },
    {
      short: 'kohaku',
      id: {sort: 73, asset: 73},
      unit: 'Crazy:B',
      type: 'idol',
      jp: {regular: '桜河 こはく', alt: ''},
      rom: {regular: 'Oukawa Kohaku', alt: ''},
      cn: {regular: '樱河 琥珀', alt: ''},
      kr: {regular: '오우카와 코하쿠', alt: ''},
      tw: {regular: '櫻河 琥珀', alt: ''},
      en: {regular: 'Kohaku Oukawa', alt: ''},
    },
    {
      short: 'niki',
      id: {sort: 74, asset: 74},
      unit: 'Crazy:B',
      type: 'idol',
      jp: {regular: '椎名 ニキ', alt: ''},
      rom: {regular: 'Shiina Niki', alt: ''},
      cn: {regular: '椎名 丹希', alt: ''},
      kr: {regular: '시이나 니키', alt: ''},
      tw: {regular: '椎名 丹希', alt: ''},
      en: {regular: 'Niki Shiina', alt: ''},
    },
    {
      short: 'rei',
      id: {sort: 81, asset: 29},
      unit: 'UNDEAD',
      type: 'idol',
      jp: {regular: '朔間 零', alt: ''},
      rom: {regular: 'Sakuma Rei', alt: ''},
      cn: {regular: '朔间 零', alt: ''},
      kr: {regular: '사쿠마 레이', alt: ''},
      tw: {regular: '朔間 零', alt: ''},
      en: {regular: 'Rei Sakuma', alt: ''},
    },
    {
      short: 'kaoru',
      id: {sort: 82, asset: 23},
      unit: 'UNDEAD',
      type: 'idol',
      jp: {regular: '羽風 薫', alt: ''},
      rom: {regular: 'Hakaze Kaoru', alt: ''},
      cn: {regular: '羽风 薰', alt: ''},
      kr: {regular: '하카제 카오루', alt: ''},
      tw: {regular: '羽風 薰', alt: ''},
      en: {regular: 'Kaoru Hakaze', alt: ''},
    },
    {
      short: 'koga',
      id: {sort: 83, asset: 16},
      unit: 'UNDEAD',
      type: 'idol',
      jp: {regular: '大神 晃牙', alt: ''},
      rom: {regular: 'Ogami Koga', alt: ''},
      cn: {regular: '大神 晃牙', alt: ''},
      kr: {regular: '오오가미 코가', alt: ''},
      tw: {regular: '大神 晃牙', alt: ''},
      en: {regular: 'Koga Ogami', alt: 'Koga Oogami'},
    },
    {
      short: 'adonis',
      id: {sort: 84, asset: 15},
      unit: 'UNDEAD',
      type: 'idol',
      jp: {regular: '乙狩 アドニス', alt: ''},
      rom: {regular: 'Otogari Adonis', alt: ''},
      cn: {regular: '乙狩 阿多尼斯', alt: ''},
      kr: {regular: '오토가리 아도니스', alt: ''},
      tw: {regular: '乙狩 阿多尼斯', alt: ''},
      en: {regular: 'Adonis Otogari', alt: ''},
    },
    {
      short: 'tomoya',
      id: {sort: 91, asset: 3},
      unit: 'Ra*bits',
      type: 'idol',
      jp: {regular: '真白 友也', alt: ''},
      rom: {regular: 'Mashiro Tomoya', alt: ''},
      cn: {regular: '真白 友也', alt: ''},
      kr: {regular: '마시로 토모야', alt: ''},
      tw: {regular: '真白 友也', alt: ''},
      en: {regular: 'Tomoya Mashiro', alt: ''},
    },
    {
      short: 'nazuna',
      id: {sort: 92, asset: 30},
      unit: 'Ra*bits',
      type: 'idol',
      jp: {regular: '仁兎 なずな', alt: ''},
      rom: {regular: 'Nito Nazuna', alt: ''},
      cn: {regular: '仁兔 成鸣', alt: ''},
      kr: {regular: '니토 나즈나', alt: ''},
      tw: {regular: '仁兔 成鳴', alt: ''},
      en: {regular: 'Nazuna Nito', alt: ''},
    },
    {
      short: 'mitsuru',
      id: {sort: 93, asset: 9},
      unit: 'Ra*bits',
      type: 'idol',
      jp: {regular: '天満 光', alt: ''},
      rom: {regular: 'Tenma Mitsuru', alt: ''},
      cn: {regular: '天满 光', alt: ''},
      kr: {regular: '텐마 미츠루', alt: ''},
      tw: {regular: '天滿 光', alt: ''},
      en: {regular: 'Mitsuru Tenma', alt: ''},
    },
    {
      short: 'hajime',
      id: {sort: 94, asset: 2},
      unit: 'Ra*bits',
      type: 'idol',
      jp: {regular: '紫之 創', alt: ''},
      rom: {regular: 'Shino Hajime', alt: ''},
      cn: {regular: '紫之 创', alt: ''},
      kr: {regular: '시노 하지메', alt: ''},
      tw: {regular: '紫之 創', alt: ''},
      en: {regular: 'Hajime Shino', alt: ''},
    },
    {
      short: 'keito',
      id: {sort: 101, asset: 21},
      unit: 'AKATSUKI',
      type: 'idol',
      jp: {regular: '蓮巳 敬人', alt: ''},
      rom: {regular: 'Hasumi Keito', alt: ''},
      cn: {regular: '莲巳 敬人', alt: ''},
      kr: {regular: '하스미 케이토', alt: ''},
      tw: {regular: '蓮巳 敬人', alt: ''},
      en: {regular: 'Keito Hasumi', alt: ''},
    },
    {
      short: 'kuro',
      id: {sort: 102, asset: 26},
      unit: 'AKATSUKI',
      type: 'idol',
      jp: {regular: '鬼龍 紅郎', alt: ''},
      rom: {regular: 'Kiryu Kuro', alt: ''},
      cn: {regular: '鬼龙 红郎', alt: ''},
      kr: {regular: '키류 쿠로', alt: ''},
      tw: {regular: '鬼龍 紅郎', alt: ''},
      en: {regular: 'Kuro Kiryu', alt: ''},
    },
    {
      short: 'souma',
      id: {sort: 103, asset: 14},
      unit: 'AKATSUKI',
      type: 'idol',
      jp: {regular: '神崎 颯馬', alt: ''},
      rom: {regular: 'Kanzaki Souma', alt: ''},
      cn: {regular: '神崎 飒马', alt: ''},
      kr: {regular: '칸자키 소마', alt: ''},
      tw: {regular: '神崎 颯馬', alt: ''},
      en: {regular: 'Souma Kanzaki', alt: ''},
    },
    {
      short: 'ibuki',
      id: {sort: 104, asset: 82},
      unit: 'AKATSUKI',
      type: 'idol',
      jp: {regular: '滝 維吹', alt: ''},
      rom: {regular: 'Taki Ibuki', alt: ''},
      cn: {regular: '泷 维吹', alt: ''},
      kr: {regular: '타키 이부키', alt: ''},
      tw: {regular: '瀧 維吹', alt: ''},
      en: {regular: 'Ibuki Taki', alt: ''},
    },
    {
      short: 'juis',
      id: {sort: 111, asset: 92},
      unit: 'MELLOW DEAR US',
      type: 'idol',
      jp: {regular: '小鹿 ジュイス', alt: ''},
      rom: {regular: 'Kojika Juis', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Juis Kojika', alt: ''},
    },
    {
      short: 'nozomi',
      id: {sort: 112, asset: 93},
      unit: 'MELLOW DEAR US',
      type: 'idol',
      jp: {regular: '円果 望見', alt: ''},
      rom: {regular: 'Madoka Nozomi', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Nozomi Madoka', alt: ''},
    },
    {
      short: 'mashu',
      id: {sort: 113, asset: 94},
      unit: 'MELLOW DEAR US',
      type: 'idol',
      jp: {regular: '久遠 舞珠', alt: ''},
      rom: {regular: 'Kuon Mashu', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Mashu Kuon', alt: ''},
    },
    {
      short: 'chitose',
      id: {sort: 114, asset: 91},
      unit: 'MELLOW DEAR US',
      type: 'idol',
      jp: {regular: '甘楽 チトセ', alt: ''},
      rom: {regular: 'Tsuzura Chitose', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Chitose Tsuzura', alt: ''},
    },
    {
      short: 'tsukasa',
      id: {sort: 121, asset: 10},
      unit: 'Knights',
      type: 'idol',
      jp: {regular: '朱桜 司', alt: ''},
      rom: {regular: 'Suou Tsukasa', alt: ''},
      cn: {regular: '朱樱 司', alt: ''},
      kr: {regular: '스오우 츠카사', alt: ''},
      tw: {regular: '朱樱 司', alt: ''},
      en: {regular: 'Tsukasa Suou', alt: ''},
    },
    {
      short: 'leo',
      id: {sort: 122, asset: 33},
      unit: 'Knights',
      type: 'idol',
      jp: {regular: '月永 レオ', alt: ''},
      rom: {regular: 'Tsukinaga Leo', alt: ''},
      cn: {regular: '月永 雷欧', alt: ''},
      kr: {regular: '츠키나가 레오', alt: ''},
      tw: {regular: '月永 雷歐', alt: ''},
      en: {regular: 'Leo Tsukinaga', alt: ''},
    },
    {
      short: 'izumi',
      id: {sort: 123, asset: 24},
      unit: 'Knights',
      type: 'idol',
      jp: {regular: '瀬名 泉', alt: ''},
      rom: {regular: 'Sena Izumi', alt: ''},
      cn: {regular: '濑名 泉', alt: ''},
      kr: {regular: '세나 이즈미', alt: ''},
      tw: {regular: '瀨名 泉', alt: ''},
      en: {regular: 'Izumi Sena', alt: ''},
    },
    {
      short: 'ritsu',
      id: {sort: 124, asset: 17},
      unit: 'Knights',
      type: 'idol',
      jp: {regular: '朔間 凛月', alt: ''},
      rom: {regular: 'Sakuma Ritsu', alt: ''},
      cn: {regular: '朔间 凛月', alt: ''},
      kr: {regular: '사쿠마 리츠', alt: ''},
      tw: {regular: '朔間 凜月', alt: ''},
      en: {regular: 'Ritsu Sakuma', alt: ''},
    },
    {
      short: 'arashi',
      id: {sort: 125, asset: 20},
      unit: 'Knights',
      type: 'idol',
      jp: {regular: '鳴上 嵐', alt: ''},
      rom: {regular: 'Narukami Arashi', alt: ''},
      cn: {regular: '鸣上 岚', alt: ''},
      kr: {regular: '나루카미 아라시', alt: ''},
      tw: {regular: '鳴上 嵐', alt: ''},
      en: {regular: 'Arashi Narukami', alt: ''},
    },
    {
      short: 'natsume',
      id: {sort: 131, asset: 38},
      unit: 'Switch',
      type: 'idol',
      jp: {regular: '逆先 夏目', alt: ''},
      rom: {regular: 'Sakasaki Natsume', alt: ''},
      cn: {regular: '逆先 夏目', alt: ''},
      kr: {regular: '사카사키 나츠메', alt: ''},
      tw: {regular: '逆先 夏目', alt: ''},
      en: {regular: 'Natsume Sakasaki', alt: ''},
    },
    {
      short: 'tsumugi',
      id: {sort: 132, asset: 39},
      unit: 'Switch',
      type: 'idol',
      jp: {regular: '青葉 つむぎ', alt: ''},
      rom: {regular: 'Aoba Tsumugi', alt: ''},
      cn: {regular: '青叶 纺', alt: ''},
      kr: {regular: '아오바 츠무기', alt: ''},
      tw: {regular: '青葉 紡', alt: ''},
      en: {regular: 'Tsumugi Aoba', alt: ''},
    },
    {
      short: 'sora',
      id: {sort: 133, asset: 37},
      unit: 'Switch',
      type: 'idol',
      jp: {regular: '春川 宙', alt: ''},
      rom: {regular: 'Harukawa Sora', alt: ''},
      cn: {regular: '春川 宙', alt: ''},
      kr: {regular: '하루카와 소라', alt: ''},
      tw: {regular: '春川 宙', alt: ''},
      en: {regular: 'Sora Harukawa', alt: ''},
    },
    {
      short: 'madara',
      id: {sort: 141, asset: 40},
      unit: 'MaM',
      type: 'idol',
      jp: {regular: '三毛縞 斑', alt: ''},
      rom: {regular: 'Mikejima Madara', alt: ''},
      cn: {regular: '三毛缟 斑', alt: ''},
      kr: {regular: '미케지마 마다라', alt: ''},
      tw: {regular: '三毛縞 斑', alt: ''},
      en: {regular: 'Madara Mikejima', alt: ''},
    },
    {
      short: 'esu',
      id: {sort: 151, asset: 81},
      unit: 'Special for Princess!',
      type: 'idol',
      jp: {regular: 'エス', alt: '冴霧 笑主'},
      rom: {regular: 'Esu', alt: 'Sagiri Esu'},
      cn: {regular: 'Esu', alt: '冴雾 笑主'},
      kr: {regular: '에스', alt: '사기리 에스'},
      tw: {regular: 'Esu', alt: '冴霧 笑主'},
      en: {regular: 'Esu', alt: 'Esu Sagiri'},
    },
    {
      short: 'kanna',
      id: {sort: 152, asset: 83},
      unit: 'Special for Princess!',
      type: 'idol',
      jp: {regular: 'カンナ', alt: '名都 神無'},
      rom: {regular: 'Kanna', alt: 'Natsu Kanna'},
      cn: {regular: 'Kanna', alt: '名都 神无'},
      kr: {regular: '칸나', alt: '나츠 칸나'},
      tw: {regular: 'Kanna', alt: '名都 神無'},
      en: {regular: 'Kanna', alt: 'Kanna Natsu'},
    },
    {
      short: 'yume',
      id: {sort: 153, asset: 84},
      unit: 'Special for Princess!',
      type: 'idol',
      jp: {regular: 'ユメ', alt: '花群 冬芽'},
      rom: {regular: 'Yume', alt: 'Hanamura Fuyume'},
      cn: {regular: 'Yume', alt: '花群 冬芽'},
      kr: {regular: '유메', alt: '하나무라 후유메'},
      tw: {regular: 'Yume', alt: '花群 冬芽'},
      en: {regular: 'Yume', alt: 'Fuyume Hanamura'},
    },
    {
      short: 'raika',
      id: {sort: 154, asset: 85},
      unit: 'Special for Princess!',
      type: 'idol',
      jp: {regular: 'ライカ', alt: '宝丈 萊香'},
      rom: {regular: 'Raika', alt: 'Houjou Raika'},
      cn: {regular: 'Raika', alt: '宝丈 莱香'},
      kr: {regular: '라이카', alt: '호죠 라이카'},
      tw: {regular: 'Raika', alt: '寶丈 萊香'},
      en: {regular: 'Raika', alt: 'Raika Hojo'},
    },
    
    /**/
    /*
    {
      short: '',
      id: {sort: , asset: },
      unit: '',
      type: '',
      jp: {regular: '', alt: ''},
      rom: {regular: '', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: '', alt: ''},
    },
    */

    {
      short: 'jin',
      id: {sort: 501, asset: 31},
      unit: 'J&A',
      type: 'teacher',
      jp: {regular: '佐賀美 陣', alt: ''},
      rom: {regular: 'Sagami Jin', alt: ''},
      cn: {regular: '佐贺美 阵', alt: ''},
      kr: {regular: '하루카와 소라', alt: ''},
      tw: {regular: '佐賀美 陣', alt: ''},
      en: {regular: 'Jin Sagami', alt: ''},
    },
    {
      short: 'akiomi',
      id: {sort: 502, asset: 32},
      unit: 'J&A',
      type: 'teacher',
      jp: {regular: '椚 章臣', alt: ''},
      rom: {regular: 'Kunugi Akiomi', alt: ''},
      cn: {regular: '门 章臣', alt: ''},
      kr: {regular: '사가미 진', alt: ''},
      tw: {regular: '椚 章臣', alt: ''},
      en: {regular: 'Akiomi Kunugi', alt: ''},
    },
    {
      short: 'nice',
      id: {sort: 503, asset: 86},
      unit: '',
      type: 'teacher',
      jp: {regular: 'ナイス・アルネブ・サンダー', alt: ''},
      rom: {regular: 'Nice Arneb Thunder', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Nice Arneb Thunder', alt: ''},
    },

    {
      short: 'tatara',
      id: {sort: 90001, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '富士田 多々良', alt: ''},
      rom: {regular: 'Fujita Tatara', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Tatara Fujita', alt: ''},
    },
    {
      short: 'orthos',
      id: {sort: 90002, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: 'オルトス', alt: ''},
      rom: {regular: 'Orthos', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Orthos', alt: ''},
    },
    {
      short: 'nero',
      id: {sort: 90003, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: 'ネロ', alt: ''},
      rom: {regular: 'Nero', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Nero', alt: ''},
    },
    {
      short: 'zeks',
      id: {sort: 90004, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: 'ゼクス', alt: ''},
      rom: {regular: 'Zeks', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Zeks', alt: ''},
    },
    {
      short: 'penetrate',
      id: {sort: 90005, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: 'ペネトレイト', alt: ''},
      rom: {regular: 'Penetrate', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Penetrate', alt: ''},
    },
    {
      short: 'onoda',
      id: {sort: 90006, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '小野田 坂道', alt: ''},
      rom: {regular: 'Onoda Sakamichi', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Sakamichi Onoda', alt: ''},
    },
    {
      short: 'makishima',
      id: {sort: 90007, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '巻島 裕介', alt: ''},
      rom: {regular: 'Makishima Yuusuke', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Yusuke Makishima', alt: ''},
    },
    {
      short: 'toudou',
      id: {sort: 90008, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '東堂 尽八', alt: ''},
      rom: {regular: 'Toudou Jinpachi', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Jinpachi Toudou', alt: ''},
    },
    {
      short: 'manami',
      id: {sort: 90009, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '真波 山岳', alt: ''},
      rom: {regular: 'Manami Sangaku', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Sangaku Manami', alt: ''},
    },
    {
      short: 'alexander',
      id: {sort: 90010, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '大和 アレクサンダー', alt: ''},
      rom: {regular: 'Yamato Alexander', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Alexander Yamato', alt: ''},
    },
    {
      short: 'hiro',
      id: {sort: 90011, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '速水 ヒロ', alt: ''},
      rom: {regular: 'Hayami Hiro', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Hiro Hayami', alt: ''},
    },
    {
      short: 'taiga',
      id: {sort: 90012, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '香賀美 タイガ', alt: ''},
      rom: {regular: 'Kougami Taiga', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Taiga Kougami', alt: ''},
    },
    {
      short: 'kakeru',
      id: {sort: 90013, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '十王院 カケル', alt: ''},
      rom: {regular: 'Juuouin Kakeru', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Kakeru Juuouin', alt: ''},
    },
    {
      short: 'shin',
      id: {sort: 90014, asset: 0},
      unit: '',
      type: 'collab',
      jp: {regular: '一条 シン', alt: ''},
      rom: {regular: 'Ichijou Shin', alt: ''},
      cn: {regular: '', alt: ''},
      kr: {regular: '', alt: ''},
      tw: {regular: '', alt: ''},
      en: {regular: 'Shin Ichijo', alt: ''},
    }
  ];

  return characters;
}

function list() {
  const ss = SpreadsheetApp.openById('1_FMwV245aaaRkpr_9l6qqPLF3EuiL40M2XPfzpnBPdg').getSheetByName('Sheet14');
  let 
    arr = [], 
    range = ss.getRange('A2:B55')
  ;

  range.getValues().forEach((row) => {
    let char = row[1], obj = namesObjArr();
    for (let x = 0; x < obj.length; x++) {
      if (obj[x].rom.regular == char) {
        arr.push([obj[x].id.asset,obj[x].rom.regular]);
      };
    };
  });
  console.log(arr);
  range.setValues(arr);
}
